on: 
  push: 
    branches: [ "master" ]

# build docker image and push to docker hub

  ci-jobs:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: action/checkout@v3
      # - name: Use with SHA 
      #   run: | 
      #     echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      # - name: Show the new tags value
      #   run: |
      #   echo "Tag value is: ${{ env.TAG }}"

# update helm repo with new imagejobs: 
